{!! Html::script('assets/vendors/general/bootstrap-select/dist/js/bootstrap-select.js') !!}
{!! Html::script('assets/js/demo2/pages/crud/forms/widgets/bootstrap-select.js') !!}
{!! Html::script('assets/vendors/general/block-ui/jquery.blockUI.js') !!}
{!! Html::script('assets/vendors/general/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') !!}
{!! Html::script('assets/app/custom/general/crud/forms/widgets/bootstrap-datepicker.js') !!}
{!! Html::script('assets/vendors/general/jquery-form/dist/jquery.form.min.js') !!}
{!! Html::script('assets/vendors/general/jquery-validation/dist/jquery.validate.js') !!}
{!! Html::script('assets/vendors/custom/components/vendors/jquery-validation/init.js') !!}
{!! Html::script('assets/vendors/general/block-ui/jquery.blockUI.js') !!}
{!! Html::script('assets/vendors/general/select2/dist/js/select2.full.js') !!}
{!! Html::script('assets/app/custom/general/crud/forms/widgets/select2.js') !!}
{!! Html::script('assets/vendors/general/inputmask/dist/jquery.inputmask.bundle.js') !!}
{!! Html::script('assets/app/custom/general/crud/forms/widgets/input-mask.js') !!}
{!! Html::script('assets/vendors/general/sweetalert2/dist/sweetalert2.min.js') !!}
{!! Html::script('assets/vendors/custom/components/vendors/sweetalert2/init.js') !!}
